CREATE TABLE `performance_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`datePreset` varchar(64) NOT NULL,
	`datePresetLabel` varchar(128) NOT NULL,
	`dateRangeSince` varchar(16) NOT NULL,
	`dateRangeUntil` varchar(16) NOT NULL,
	`isPartial` boolean NOT NULL DEFAULT false,
	`amountSpent` decimal(12,2) NOT NULL,
	`impressions` int NOT NULL,
	`reach` int NOT NULL,
	`frequency` decimal(6,2) NOT NULL,
	`clicksAll` int NOT NULL,
	`linkClicks` int NOT NULL,
	`ctrAll` decimal(6,4) NOT NULL,
	`ctrLink` decimal(6,4) NOT NULL,
	`cpm` decimal(8,2) NOT NULL,
	`cpcAll` decimal(8,4) NOT NULL,
	`cpcLink` decimal(8,4) NOT NULL,
	`leads` int NOT NULL,
	`costPerLead` decimal(8,2) NOT NULL,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `performance_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `snapshot_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`snapshotId` int NOT NULL,
	`campaignId` varchar(32) NOT NULL,
	`campaignName` text NOT NULL,
	`shortName` varchar(128) NOT NULL,
	`objective` varchar(64) NOT NULL,
	`status` varchar(32) NOT NULL,
	`amountSpent` decimal(12,2) NOT NULL,
	`impressions` int NOT NULL,
	`reach` int NOT NULL,
	`frequency` decimal(6,2) NOT NULL,
	`clicksAll` int NOT NULL,
	`linkClicks` int NOT NULL,
	`ctrAll` decimal(6,4) NOT NULL,
	`ctrLink` decimal(6,4) NOT NULL,
	`cpm` decimal(8,2) NOT NULL,
	`cpcAll` decimal(8,4) NOT NULL,
	`cpcLink` decimal(8,4) NOT NULL,
	`leads` int NOT NULL,
	`costPerLead` decimal(8,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `snapshot_campaigns_id` PRIMARY KEY(`id`)
);
